events {}
http {
    upstream active_backend {
        # Switches between 5001 (Blue) and 5002 (Green)
        server 127.0.0.1:5001;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://active_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
